apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dora-metrics-cluster
  labels:
    app: dora-metrics
    app.kubernetes.io/name: dora-metrics
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: dora-metrics
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["appprojects"]
    verbs: ["get", "list"]
