apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dora-metrics-cluster
  labels:
    app: dora-metrics
    app.kubernetes.io/name: dora-metrics
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: dora-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dora-metrics-cluster
subjects:
  - kind: ServiceAccount
    name: dora-metrics
    namespace: konflux-dora-metrics
