apiVersion: v1
kind: ServiceAccount
metadata:
  name: dora-metrics
  namespace: konflux-dora-metrics
  labels:
    app: dora-metrics
    app.kubernetes.io/name: dora-metrics
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: dora-metrics
